name = "sokohubwebsite"
main = ".open-next/worker.js"
compatibility_date = "2026-01-06"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://rmgtdipwxieqlqkxyohv.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtZ3RkaXB3eGllcWxxa3h5b2h2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMDA4NDEsImV4cCI6MjA4NDU3Njg0MX0.IqHRLJwadbx_P4fBrZFaLrSGLjnkukavukGriLy9j4U"
NEXT_PUBLIC_SITE_URL = "https://sokohubkenya.com"
NEXT_PUBLIC_SITE_NAME = "Sokohub Kenya"
NEXT_PUBLIC_WHATSAPP_NUMBER = "254707874828"
NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET = "product-images"
NEXT_PUBLIC_GOOGLE_ADS_ID = "AW-17761819504"
