name = "toto-toys"
main = ".open-next/worker.js"
compatibility_date = "2026-01-06"
compatibility_flags = ["nodejs_compat"]

assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://tafojbtftmihrheeyoky.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhZm9qYnRmdG1paHJoZWV5b2t5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3Mzk3MTYsImV4cCI6MjA2MDMxNTcxNn0.vdL2odCYREv1GykTt8wx76lmhaHmDkBYcC65L4Z_vXo"
NEXT_PUBLIC_SITE_URL = "https://toto.co.ke"
NEXT_PUBLIC_SITE_NAME = "Toto Toys"
NEXT_PUBLIC_WHATSAPP_NUMBER = "254756161300"
NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET = "product-images"
NEXT_PUBLIC_GOOGLE_ANALYTICS_ID = "G-YPJGEPLZGH"